after_script:
  - docker images

before_script:
  - IMAGE="node:$VERSION"

env:
  - VERSION=4/onbuild
  - VERSION=4/slim
  - VERSION=5/onbuild
  - VERSION=5/slim

language: bash

script:
  - docker build -t "$IMAGE" "$VERSION"
  - docker build "test/$VERSION"

services: docker
