after_script:
  - docker images

before_script:
  - IMAGE="node:$VERSION"

env:
  - VERSION=4/onbuild
  - VERSION=4/onbuild-yarn
  - VERSION=4/slim
  - VERSION=4/slim-yarn
  - VERSION=4/test
  - VERSION=4/test-yarn
  - VERSION=6/onbuild
  - VERSION=6/onbuild-yarn
  - VERSION=6/slim
  - VERSION=6/slim-yarn
  - VERSION=6/test
  - VERSION=6/test-yarn
  - VERSION=7/onbuild
  - VERSION=7/onbuild-yarn
  - VERSION=7/slim
  - VERSION=7/slim-yarn
  - VERSION=7/test
  - VERSION=7/test-yarn
  - VERSION=8/onbuild
  - VERSION=8/onbuild-yarn
  - VERSION=8/slim
  - VERSION=8/slim-yarn
  - VERSION=8/test
  - VERSION=8/test-yarn

language: bash

script:
  - docker build -t "$IMAGE" "$VERSION"
  - "[[ -f test/$VERSION/Dockerfile ]] && docker build test/$VERSION || true"

services: docker
