after_script:
  - docker images

before_script:
  - IMAGE="node:$VERSION"

env:
  - VERSION=4/onbuild
  - VERSION=4/slim
  - VERSION=4/test
  - VERSION=5/onbuild
  - VERSION=5/slim
  - VERSION=5/test

language: bash

script:
  - docker build -t "$IMAGE" "$VERSION"
  - "[[ -f test/$VERSION/Dockerfile ]] && docker build test/$VERSION || true"

services: docker
